
services:
  # 1 Придумываем название для проекта
  bank_api:
    # 2 Замена Команды "docker build -t my-bank-app"
    # Точка означает: "Возми Dockerfile из текущей папки и собери образ"
    build: .
    # 3 Замена ФЛАГА "--name go_bank_container"
    # Даем запущеному контейнеру имя
    container_name: go_bank_container
    # 4. Замена флага "-p 9091:9091"
    # Связываем порт твоего компьютера с портом внутри контейнера
    ports:
        - "9091:9091"
      # 5 Дополнительная Крутая Инструкция
      # Если в твоем Go-file случится паника и он упадет
      # Docker Compose сам мгновенно подымет
    restart: always
